config/routes.rb
Rails.application.routes.draw do
  root 'geo_maps#home'

  get 'about' => 'geo_maps#about'

  get 'maps' => 'geo_maps#maps'

  get 'location' => 'geo_maps#location'

  get 'ask' => 'geo_maps#ask'

  get 'show', to: 'geo_maps#show'

  get 'search' => 'geo_maps#search'

  get 'display', to: 'geo_maps#display'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/geo_maps_controller.rb
class GeoMapsController < ApplicationController
  def home
  end

  def about
  end

  def maps
    @my_map = (rand(40.5555...40.7777).round(4))
    @my_map2 = (rand(-73.9999...-73.8888).round(4))
    @fun_map = "https://www.google.com/maps/embed/v1/view?key=AIzaSyDu-oMa6E3bBAR2QV8E-oZtyPhhY-FMq6A&center=#{@my_map},#{@my_map2}&zoom=18&maptype=satellite"
  end

  def location
  end

  def ask
  end

  def show
    @hood = params[:hood]
    @coffee = "https://www.google.com/maps/embed/v1/search?key=AIzaSyDu-oMa6E3bBAR2QV8E-oZtyPhhY-FMq6A&q=coffee+shops+in+#{@hood}"
  end

  def search
  end

  def display
    @location = params[:location]
    @what = params[:what]
    @dogos ="https://www.google.com/maps/embed/v1/search?key=AIzaSyDu-oMa6E3bBAR2QV8E-oZtyPhhY-FMq6A&q=#{@what}+in+#{@location}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geo_maps_helper.rb
module GeoMapsHelper
end

app/views/geo_maps/about.html.erb
<h1>GeoMaps#about</h1>
<p>Find me in app/views/geo_maps/about.html.erb</p>

app/views/geo_maps/ask.html.erb
<body>
<h1> Coffee Shops! </h1>

<section class='container'>

	<%= form_tag show_path, method: "get", html: { class: "form" } do %>
 	<div class="form-group col-sm-6 col-md-offset-3">
   	<%= text_field_tag(:hood, " ", placeholder: "Enter Neighborhood", class: "form-control") %>
 	</div>

 	<center><div class="form-group col-sm-12">
 	<%=submit_tag "Search", class: "btn btn-info"%>
	<% end %>
	</div></center>
</section>
</body>

app/views/geo_maps/display.html.erb
<body>
<h1> <%= @what %> in <%= @location %></h1>

<section class='container' style='padding-top: 2em;'>
	<center><iframe
  	width="800"
  	height="600"
  	frameborder="0" style="border:0"
  	src="<%= @dogos %>">
</iframe></center>
</section>
</body>

app/views/geo_maps/home.html.erb
<body>
<h1> Map Lesson </h1>
<p> GeoJson, API's, and Dynamic Web Dev </p>

<p style= 'font-size: 1em;'> Where Are The Bark Parks </p>

<section class='container' style='padding-top: 2em;'>
	<center><iframe
  	width="600"
  	height="450"
  	frameborder="0" style="border:0"
  	src="https://www.google.com/maps/embed/v1/search?key=AIzaSyDu-oMa6E3bBAR2QV8E-oZtyPhhY-FMq6A&q=dog+runs+in+nyc" allowfullscreen>
</iframe></center>
</section>



</body>

app/views/geo_maps/location.html.erb
<body>
<h1> Green Buildings in NYC </h1>

<script async src="//jsfiddle.net/foxportal/5L07d5xj/embed/"></script>
</body>

app/views/geo_maps/maps.html.erb
<body>
<h1> Random Location </h1>
	<section class='container'>
    	<center><iframe
      		width="800"
      		height="400"
      		src="<%= @fun_map %>"/>
    	</iframe></center>
  	</section>
</body>

app/views/geo_maps/search.html.erb
<body>
<h1> Doggos! </h1>
<section class ='container'>
	<%= form_tag display_path, method: "get", html: { class: "form" } do %>
 	<div class="form-group col-sm-6 col-md-offset-3">
   	<%= text_field_tag(:location, "", placeholder: "Enter Neighborhood", class: "form-control") %>
 	</div>

 	<div class="form-group col-sm-6 col-md-offset-3">
   	<%= text_field_tag(:what, "", placeholder: "Enter What", class: "form-control") %>
 	</div>

 	<center><div class="form-group col-sm-12">
 	<%=submit_tag "Search", class: "btn btn-info"%>
	<% end %>
	</div></center>
</section>
</body>

app/views/geo_maps/show.html.erb
<h1> Coffee for You in <%= @hood %></h1>

<section class='container' style='padding-top: 2em;'>
	<center><iframe
  	width="800"
  	height="600"
  	frameborder="0" style="border:0"
  	src="<%= @coffee %>">
</iframe></center>
</section>

app/views/layouts/_footer.html.erb
<footer class="footer container">
  <small>
   Dwight IB: <a href="https://github.com/kyle1james/ib">Artist & Technologist</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Map 101", '/ask' %></li>
      <li><%= link_to "Map 200",   '/search' %></li>
      <li><%= link_to "Random",   '/maps' %></li>
      <li><%= link_to "Lesson", '/location' %></li>
      <li><%= link_to "Home", '/' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="container">
    <%= yield %>
  </body>
  <%= render 'layouts/footer' %>
</html>